// Trading Signals Generator using Gemini API
// Displays signals on the frontend

const SIGNALS_API = '/api/generate-signals'; // Your backend endpoint

async function loadSignals() {
    const container = document.getElementById('signals-container');
    
    try {
        // Fetch pre-generated signals (generated by GitHub Actions daily)
        const response = await fetch('/data/signals.json');
        const signals = await response.json();
        
        container.innerHTML = signals.slice(0, 3).map(signal => `
            <div class="signal-card ${signal.direction}">
                <div class="signal-pair">${signal.pair}</div>
                <div class="signal-direction ${signal.direction}">
                    ${signal.direction === 'buy' ? '📈 BUY' : '📉 SELL'}
                </div>
                <div class="signal-details">
                    <p><strong>Entry:</strong> ${signal.entry}</p>
                    <p class="blurred"><strong>Take Profit:</strong> VIP Only</p>
                    <p class="blurred"><strong>Stop Loss:</strong> VIP Only</p>
                </div>
                <div class="signal-time">Posted: ${signal.time}</div>
            </div>
        `).join('');
        
    } catch (error) {
        container.innerHTML = `
            <div class="signal-card">
                <p>📊 Signals updating... Check back soon!</p>
            </div>
        `;
    }
}

// Countdown timer
function updateCountdown() {
    const now = new Date();
    const midnight = new Date();
    midnight.setHours(24, 0, 0, 0);
    
    const diff = midnight - now;
    const hours = Math.floor(diff / (1000 * 60 * 60));
    const minutes = Math.floor((diff % (1000 * 60 * 60)) / (1000 * 60));
    const seconds = Math.floor((diff % (1000 * 60)) / 1000);
    
    document.getElementById('countdown').textContent = 
        `${hours.toString().padStart(2, '0')}:${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')}`;
}

// Initialize
document.addEventListener('DOMContentLoaded', function() {
    loadSignals();
    setInterval(updateCountdown, 1000);
});
